export const PRODUCTS = [
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: "Aleo Vera Cream 500ml",
    category: ["Beauty and Personal Care", "Skin Care", "Creams and Lotions"],
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Male Hair Gel",
    category: ["Beauty and Personal Care", "Hair", "Oils and Gels"],
    vendor: "Garnier",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Keeps your hair as you want for 2 days straight.",
    sold: "1K",
    stock: "560",
    rating: "1.5",
    reviews: "876",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Smart TV 43" Super AMOLED Android 11`,
    category: ["Electronics", "Home Appliances", "TV"],
    vendor: "Samsung",
    delivery: "NPR 100",
    price: "NPR 750",
    description: "Perfect TV for you to watch FIFA world cup 2022",
    sold: "150K",
    stock: "123K",
    rating: "4.8",
    reviews: "50K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
  {
    title: `Acer Predator Helios 300 | 12th Gen Gaming Laptop`,
    category: ["Electronics", "Laptops and Accessories", "Gaming Laptops"],
    vendor: "Acer",
    delivery: "NPR 1565",
    price: "NPR 296750",
    description: "Super reliable and efficient gaming laptop.",
    sold: "5K",
    stock: "10K",
    rating: "4.7",
    reviews: "1.5K",
  },
];
