export const PRODUCTS = [
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "40x60 Laptop Table",
    vendor: "Biotique Company",
    delivery: "NPR 65",
    price: "NPR 250",
    description:
      "Good table with adjustable height 70 to 90cm. Sturdy build and premium finish.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
  {
    title: "Aleo Vera Cream 500ml",
    vendor: "Biotique Company",
    delivery: "FREE",
    price: "NPR 250",
    description:
      "A very nice cream for glowing and smooth skin. Suitable for all ages and skin types.",
    sold: "1.5K",
    stock: "500",
    rating: "3.5",
    reviews: "986",
  },
];
